config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

		  devise_for :users
		  
		  root 'posts#index', as: 'home'

		  get 'aboutus' => 'users#aboutus', as: 'about'

		  resources :posts

	  end

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category_type.rb
class CategoryType < ApplicationRecord
	has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true


	belongs_to :category_type,  optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  respond_to :html, :js
  
  protect_from_forgery with: :exception    # Prevent CSRF attacks by raising an exception.

  before_action :authenticate_user!	
  before_action :set_locale


 	def default_url_options
 		{locale: I18n.locale}
 	end

 	def set_locale
 		I18n.locale = extract_locale || I18n.default_locale
 	end

 	def extract_locale
 		parsed_locale = params[:locale]
 		I18n.available_locales.map(&:to_s).include?(parsed_locale) ?
 		parsed_locale.to_sym :
 		nil
 	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user! ,except: [:index, :show, :homepage]

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create

		@post = Post.new(post_params)
		@post.feature_image = params[:post][:feature_image].original_filename

		if(@post.save)
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		
		@post = Post.find(params[:id])
		
		if(@post.update(post_params))
			if(!params[:post][:feature_image].nil?)
				@post.feature_image = params[:post][:feature_image].original_filename
				@post.save
				redirect_to @post
			else
				redirect_to @post
			end	
		else
			render 'edit'
		end	
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title,:body,:category_id)

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Post IT</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="/javascripts/jquery.min.js"></script>
    
    <link rel="stylesheet" href="/css/style.css">
  </head>

  <body>

    <nav class="navbar navbar-default">
        <div class="container">

            <div class="navbar-header">

              <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">PostIt</a>
            </div>

            <div id="navbar" class="collapse navbar-collapse">

              <ul class="nav navbar-nav">
                  <li><%= link_to t('feeds'), home_path %></li>
                  <li><%= link_to t('create_post'), new_post_path %></li>
              </ul>

              <ul class="nav navbar-nav navbar-right">
                  <p class="navbar-text float-right">
                    <% if user_signed_in? %>
                      Logged in as <strong><%= current_user.email %></strong>.
                      <%= link_to t('edit_profile'), edit_user_registration_path, :class => 'navbar-link' %> |
                      <%= link_to t('logout'), destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                    <% else %>
                      <%= link_to t('sign_up'), new_user_registration_path, :class => 'navbar-link'  %> |
                      <%= link_to t('login'), new_user_session_path, :class => 'navbar-link'  %>
                    <% end %>
                  </p>
              </ul>

            </div>

        </div>
    </nav>

    <div class="container">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>

        <%= yield %>
    </div>

     <script>
      
        $(document).ready(function(){
            $('.navbar-toggle').click(function(){
              $('#navbar').toggleClass('in')
            })
        });

     </script>


  </body>
</html>

app/views/posts/edit.html.erb
<h3><%= t('edit_post')%></h3>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
	
	<% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger"><%= msg %></div>
        <% end %>  
  	<% end %>

	<p>
		<%= f.label :title, t('title') %><br>
		<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :body, t('body') %><br>
		<%= f.text_area(:body, {:class => 'form-control'})  %>
	</p>

	<p>
		<%= f.label :Category, t('category') %><br>
		<%= f.collection_select(:category_id, CategoryType.all, :id, :category_name, {:selected => @post.category_id.to_i}, {class: 'form-control'})%>
	</p>

	<p>
		<%= f.label :Image, t('feature_image') %><br>
		<%= f.file_field(:feature_image) %>
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-primary'})%>
	</p>

<% end %>

app/views/posts/index.html.erb
<h3><%= t('posts')%></h3>
	<select class="lang-select">
	    <option><%= t('change_lang')%></option>
	    <option><%= link_to "English", home_path(locale: :en) %></option>
	    <option><%= link_to "Français", home_path(locale: :fr) %></option>
	</select>
	
<% if !@posts.nil? && !@posts.blank? %>

	<% @posts.each do |post|%>
	<% category = CategoryType.where("id=?", post.category_id).select("category_name").first%>
		
		<div class="well clearfix">

			<div class="col-md-4 col-xs-12">
				<% if !post.feature_image.nil?%>
					<img src="/images/<%= post.feature_image%>" class="img-responsive"> 
				<%else%>
					<img src="/images/abc.jpg" class="img-responsive">
				<%end%>
			</div>

			<div class="col-md-8 col-xs-12">
				<h3><%= post.title%></h3>
				<label class="type-b" disabled = "true"><%= category.category_name%></label>
				<p class="c-body"><%= post.body%></p>

				<%=link_to t('read_more'), post_path(post), :class => 'btn btn-default' %>
			</div>	

		</div>

	<%end%>

<%else%>
	<div class="well clearfix">
		<p><%= t('no_post_msg')%></p>
	</div>

<%end%>

<script>
      $(document).ready(function(){
         
          $('.lang-select').change(function(){

            var lan = $('.lang-select').val();
            
              if (lan == "English"){
                window.location.href = "/en";
              }   
              else if(lan == "Français"){
                window.location.href = "/fr";
              }
          });
      });

</script>

app/views/posts/new.html.erb
<h3><%= t('create_post')%></h3>

<%= form_for :post, url: posts_path do |f| %>
	
	
		<% if @post.errors.any? %>
	        <% @post.errors.full_messages.each do |msg| %>
	          <div class="alert alert-danger"><%= msg %></div>
	        <% end %>  
	  	<% end %>

		<p>
			<%= f.label :title, t('title') %><br>
			<%= f.text_field(:title, {:class => 'form-control'}) %>
		</p>

		<p>
			<%= f.label :body, t('body') %><br>
			<%= f.text_area(:body, {:class => 'form-control'})  %>
		</p>

		<p>
			<%= f.label :Category, t('category') %><br>
			<%= f.collection_select(:category_id, CategoryType.all, :id, :category_name, {selected: CategoryType.first.try(:category_name)}, {class: 'form-control'})%>
		</p>
		
		<p>
			<%= f.label :Image, t('feature_image') %><br>
			<%= f.file_field :feature_image %>
		</p>
	
	<p>
		<%= f.submit({:class => 'btn btn-primary'})%>
	</p>


<% end %>

app/views/posts/show.html.erb
<br><br>
<div class="well clearfix">
<% category = CategoryType.where("id=?", @post.category_id).select("category_name").first%>
	<div class="col-md-4 col-xs-12">
			<img src="/images/<%= @post.feature_image%>" class="img-responsive">
	</div>

	<div class="col-md-8 col-xs-12">
		<h3><%= @post.title%></h3>
		<label class="type-b" disabled = "true"> <%= category.category_name%></label>
		<p><%= @post.body%></p>
		<hr>
		<%= link_to t('edit_button'), edit_post_path(@post), :class => 'btn btn-default' %>
		<%= link_to t('delete_button'), post_path(@post), method: :delete, data:{confirm: 'Do you want to delete the post?'}, :class => 'btn btn-danger' %>
	</div>
</div>